### ISSUE TITLE
why there is no scp 3114?

### ISSUE THREAD

**Issue by thisisyoursus** [bladuk/ScpsInfoDisplay#7]
![20240205164510_1](https://github.com/bladuk/ScpsInfoDisplay/assets/114288684/f23b73da-fff6-4339-9620-54a3c6f037ae)

**Comment by thisisyoursus** [comment]
ok just add Scp3114: <color=#D51D1D>SCP-3114 [%healthpercent%%] %distance%</color>

**Comment by bladuk** [comment]
Will add this at default configs in the next update.
